--FUNCION PARA MOSTRAR REGISTRO POR ID Y MOSTRAR SOLO LOS ACTIVOS
CREATE FUNCTION fn_Aulas_SeleccionarPorId
(
	@NumeroAula VARCHAR(10)
)
RETURNS TABLE
AS
RETURN
	SELECT * FROM Aulas
	WHERE NumeroAula = @NumeroAula
	AND Activo = 1