--FUNCION PARA MOSTRAR DE LA TABLA TODOS LOS REGISTROS ACTIVOS
CREATE FUNCTION[fn_CursosEnMatriculas_SeleccionarTodos]()
RETURNS TABLE
AS
RETURN 
	SELECT * FROM CursosEnMatriculas A WHERE A.Activo = 1
GO