--FUNCION PARA MOSTRAR REGISTRO POR ID Y MOSTRAR SOLO LOS ACTIVOS
CREATE FUNCTION fn_Carreras_SeleccionarPorId
(
	@CodigoCarrera INT
)
RETURNS TABLE
AS
RETURN
	SELECT * FROM Carreras
	WHERE CodigoCarrera = @CodigoCarrera
	AND Activo = 1