--FUNCION PARA MOSTRAR REGISTRO POR ID Y MOSTRAR SOLO LOS ACTIVOS
CREATE FUNCTION fn_Profesores_SeleccionarPorId
(
	@CedulaProfesor VARCHAR(15)
)
RETURNS TABLE
AS
RETURN
	SELECT * FROM Profesores
	WHERE CedulaProfesor = @CedulaProfesor
	AND Activo = 1