--FUNCION PARA MOSTRAR REGISTRO POR ID Y MOSTRAR SOLO LOS ACTIVOS
CREATE FUNCTION fn_Sedes_SeleccionarPorId
(
	@CodigoSede VARCHAR(10)
)
RETURNS TABLE
AS
RETURN
	SELECT * FROM Sedes
	WHERE CodigoSede = @CodigoSede
	AND Activo = 1