--VISTA EN DONDE SE MUESTRAN SOLO LOS REGISTROS LLAMADOS POR EL ID QUE SE ENCUENTRAN ACTIVOS EN LA TABLA "CURSOS EN AULAS"
CREATE VIEW vw_CursosEnAulas_SeleccionarUnRegistroPorId AS SELECT * FROM CursosEnAulas WHERE CodigoCurso = 'A4352'
and activo =1