--VISTA EN DONDE SE MUESTRAN SOLO LOS REGISTROS LLAMADOS POR EL ID QUE SE ENCUENTRAN ACTIVOS EN LA TABLA CICLO LECTIVO
CREATE VIEW vw_CicloLectivos_SeleccionarUnRegistroPorId AS SELECT * FROM CicloLectivos WHERE NumeroCiclo = '1'
and activo = 1