--VISTA EN DONDE SE MUESTRAN SOLO LOS REGISTROS LLAMADOS POR EL ID QUE SE ENCUENTRAN ACTIVOS EN LA TABLA CURSOS CON PROFESOR
CREATE VIEW vw_CursosConProfesores_SeleccionarUnRegistroPorId AS SELECT * FROM CursosConProfesores WHERE CodigoCurso = 'B6138'
and activo =1