--VISTA EN DONDE SE MUESTRAN SOLO LOS REGISTROS LLAMADOS POR EL ID QUE SE ENCUENTRAN ACTIVOS EN LA TABLA CURSOS EN MATRICULAS
CREATE VIEW vw_CursosEnMatriculas_SeleccionarUnRegistroPorId AS SELECT * FROM CursosEnMatriculas WHERE NumeroMatricula = 1
and activo = 1