--VISTA EN DONDE SE MUESTRAN SOLO LOS REGISTROS LLAMADOS POR EL ID QUE SE ENCUENTRAN ACTIVOS EN LA TABLA "MATRICULA"
CREATE VIEW vw_Matriculas_SeleccionarUnRegistroPorId AS SELECT * FROM Matriculas WHERE CedulaEstudiante = '5-0432-0608'
and activo =1