--VISTA EN DONDE SE MUESTRAN SOLO LOS REGISTROS LLAMADOS POR EL ID QUE SE ENCUENTRAN ACTIVOS EN LA TABLA "PROFESOR"
CREATE VIEW vw_Profesores_SeleccionarUnRegistroPorId AS SELECT * FROM Profesores WHERE CedulaProfesor = '5-8932-5634'
and activo =1